packages:
  - functions

ignoredBuiltDependencies:
  - '@vaadin/vaadin-usage-statistics'

onlyBuiltDependencies:
  - '@firebase/util'
  - esbuild
  - protobufjs

overrides:
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  fast-xml-parser@>=4.3.6 <=5.3.3: '>=5.3.4'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  happy-dom@<20.0.0: '>=20.0.0'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  jws@<3.2.3: '>=3.2.3'
  jws@=4.0.0: '>=4.0.1'
  lodash-es@>=4.0.0 <=4.17.22: '>=4.17.23'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  node-forge@<1.3.2: '>=1.3.2'
  qs@<6.14.1: '>=6.14.1'
  storybook@>=9.0.0 <9.1.17: '>=9.1.17'
